#### Makefile
OBJS = cuda_bandwidth_nvml_pthreads_power_main.o cuda_bandwidth_nvml_measure_power.o cuda_bandwidth_nvml_power_kernel.o
HEADER = ./cuda_bandwidth_nvml_power_kernel_define.h

NVMLLIB = -L
NVMINCLUDE = -I
EXEC = run

$(EXEC): $(OBJS) $(HEADER)
	nvcc  -o $@  $(OBJS) -lnvidia-ml 

cuda_bandwidth_nvml_power_kernel.o: cuda_bandwidth_nvml_power_kernel.cu $(HEADER) cuda_bandwidth_nvml_power_kernel_functions.h  
	nvcc  -c cuda_bandwidth_nvml_power_kernel.cu -lcublas 
cuda_bandwidth_nvml_measure_power.o: cuda_bandwidth_nvml_measure_power.cu $(HEADER) 
	nvcc -c cuda_bandwidth_nvml_measure_power.cu -DMKL_ILP64 $(NVMINCLUDE) $(NVMLLIB) 
cuda_bandwidth_nvml_pthreads_power_main.o: cuda_bandwidth_nvml_pthreads_power_main.cu cuda_bandwidth_nvml_measure_power.cu cuda_bandwidth_nvml_power_kernel.cu $(HEADER)
	nvcc -c cuda_bandwidth_nvml_pthreads_power_main.cu 
default: $(EXEC)

clean:
	rm -f *.o run
